name: whether_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^7.6.2 
  google_maps_flutter: ^2.9.0
  google_places_flutter: ^2.0.9
  http: ^1.2.2
  intl: ^0.19.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets\sky.jpg
   - assets\drawerimage.avif
   - assets\whethericon.png
   - assets\newimage.jpg
   - assets\mostly.png
   - assets\Image.png